add a success/fail check on deployment

diff --git a/.github/workflows/deploy-express.yml b/.github/workflows/deploy-express.yml
--- a/.github/workflows/deploy-express.yml
+++ b/.github/workflows/deploy-express.yml
@@ -48,4 +48,14 @@ jobs:
           ssh -t ${{ secrets.DO_USERNAME }}@eduquilt.com 'echo COUCHDB_SERVER=${{ secrets.COUCHDB_SERVER }} >> /home/skuilder/.env.development.local'
         
           ssh -t ${{ secrets.DO_USERNAME }}@eduquilt.com 'echo ${{ secrets.DO_PASSWORD }} | sudo -S systemctl restart eqExpress'
+      
+          sleep 10s
+          
+          if curl eduquilt.com/express | grep -q ${{ github.SHA }}; then
+              echo "Success. Current version found in production"
+              exit 0 
+          else
+              echo "Error! Current version not reported by production."
+              exit 1 
+          fi
       # todo: toss a buildinfo.md file into the (ecount+1) folder, linking PR, listing time, logging build errors, etc
